name: qimr-teaching-2024
channels:
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - _r-mutex=1.0.1
  - anndata=0.10.8
  - anyio=4.4.0
  - appnope=0.1.4
  - argcomplete=3.4.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - array-api-compat=1.7.1
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - atk-1.0=2.38.0
  - attrs=23.2.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.15
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.2
  - aws-c-io=0.14.9
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.10
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.12
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.11.1
  - azure-identity-cpp=1.6.0
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - beautifulsoup4=4.12.3
  - bioconductor-beachmat=2.18.0
  - bioconductor-biobase=2.62.0
  - bioconductor-biocfilecache=2.10.1
  - bioconductor-biocgenerics=0.48.1
  - bioconductor-biocneighbors=1.20.0
  - bioconductor-biocparallel=1.36.0
  - bioconductor-biocsingular=1.18.0
  - bioconductor-bluster=1.12.0
  - bioconductor-complexheatmap=2.18.0
  - bioconductor-data-packages=20231203
  - bioconductor-delayedarray=0.28.0
  - bioconductor-delayedmatrixstats=1.24.0
  - bioconductor-dropletutils=1.22.0
  - bioconductor-ebimage=4.44.0
  - bioconductor-edger=4.0.16
  - bioconductor-genomeinfodb=1.38.1
  - bioconductor-genomeinfodbdata=1.2.11
  - bioconductor-genomicranges=1.54.1
  - bioconductor-glmgampoi=1.14.0
  - bioconductor-hdf5array=1.30.0
  - bioconductor-hoodscanr=1.0.0
  - bioconductor-infercnv=1.18.1
  - bioconductor-iranges=2.36.0
  - bioconductor-limma=3.58.1
  - bioconductor-matrixgenerics=1.14.0
  - bioconductor-metapod=1.10.0
  - bioconductor-rhdf5=2.46.1
  - bioconductor-rhdf5filters=1.14.1
  - bioconductor-rhdf5lib=1.24.0
  - bioconductor-s4arrays=1.2.0
  - bioconductor-s4vectors=0.40.2
  - bioconductor-scaledmatrix=1.10.0
  - bioconductor-scater=1.30.1
  - bioconductor-scran=1.30.0
  - bioconductor-scuttle=1.12.0
  - bioconductor-singlecellexperiment=1.24.0
  - bioconductor-sparsearray=1.2.2
  - bioconductor-sparsematrixstats=1.14.0
  - bioconductor-spatialexperiment=1.12.0
  - bioconductor-splatter=1.26.0
  - bioconductor-summarizedexperiment=1.32.0
  - bioconductor-xvector=0.42.0
  - bioconductor-zlibbioc=1.48.0
  - biopython=1.83
  - blast=2.6.0
  - bleach=6.1.0
  - blosc=1.21.5
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.6.2
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - cctools_osx-64=986
  - certifi=2024.6.2
  - cffi=1.16.0
  - cfitsio=4.4.0
  - charset-normalizer=3.3.2
  - clang=18.1.7
  - clang-18=18.1.7
  - clang_impl_osx-64=18.1.7
  - clang_osx-64=18.1.7
  - clangxx=18.1.7
  - clangxx_impl_osx-64=18.1.7
  - clangxx_osx-64=18.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - compiler-rt=18.1.7
  - compiler-rt_osx-64=18.1.7
  - contourpy=1.2.1
  - curl=8.8.0
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.6.2
  - fftw=3.3.10
  - fmt=10.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.53.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.12
  - geos=3.12.1
  - geotiff=1.7.3
  - get-annotations=0.1.2
  - gettext=0.22.5
  - gettext-tools=0.22.5
  - gflags=2.2.2
  - gfortran_impl_osx-64=12.3.0
  - gfortran_osx-64=12.3.0
  - ghostscript=10.03.1
  - giflib=5.2.2
  - glog=0.7.1
  - glpk=5.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - graphviz=11.0.0
  - gtk2=2.24.33
  - gts=0.7.6
  - h11=0.14.0
  - h2=4.1.0
  - h5py=3.11.0
  - harfbuzz=8.5.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - icu=73.2
  - idna=3.7
  - imagemagick=7.1.1_33
  - importlib-metadata=7.2.0
  - importlib_metadata=7.2.0
  - importlib_resources=6.4.0
  - ipykernel=6.29.4
  - ipython=8.25.0
  - ipywidgets=8.1.3
  - isl=0.26
  - isoduration=20.11.0
  - jags=4.3.2
  - jbig=2.1
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jq=1.7.1
  - json-c=0.17
  - json5=0.9.25
  - jsonpointer=3.0.0
  - jsonschema=4.22.0
  - jsonschema-specifications=2023.12.1
  - jsonschema-with-format-nongpl=4.22.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.2
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.2.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.2
  - jupyterlab_widgets=3.0.11
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - ld64_osx-64=711
  - legacy-api-wrap=1.4
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.3
  - libarchive=3.7.4
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.22.5
  - libasprintf-devel=0.22.5
  - libblas=3.9.0
  - libboost-headers=1.85.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang-cpp18.1=18.1.7
  - libcrc32c=1.1.2
  - libcurl=8.8.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgd=2.3.3
  - libgdal=3.9.0
  - libgettextpo=0.22.5
  - libgettextpo-devel=0.22.5
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=12.3.0
  - libgfortran5=13.2.0
  - libgit2=1.8.1
  - libglib=2.80.2
  - libgoogle-cloud=2.25.0
  - libgoogle-cloud-storage=2.25.0
  - libgrpc=1.62.2
  - libhwloc=2.10.0
  - libiconv=1.17
  - libintl=0.22.5
  - libintl-devel=0.22.5
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libllvm18=18.1.7
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.27
  - libparquet=16.1.0
  - libpng=1.6.43
  - libpq=16.3
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - librsvg=2.58.1
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialite=5.1.0
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.6.0
  - libudunits2=2.2.28
  - libutf8proc=2.8.0
  - libv8=8.9.83
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.16
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - llvm-openmp=18.1.8
  - llvm-tools=18.1.7
  - llvmlite=0.43.0
  - lz4-c=1.9.4
  - lzo=2.10
  - make=4.3
  - markupsafe=2.1.5
  - matplotlib-base=3.8.4
  - matplotlib-inline=0.1.7
  - minizip=4.0.7
  - mistune=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - munkres=1.1.4
  - muscle=5.1
  - natsort=8.4.0
  - nbclient=0.10.0
  - nbconvert=7.16.4
  - nbconvert-core=7.16.4
  - nbconvert-pandoc=7.16.4
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nlopt=2.7.1
  - notebook=7.2.1
  - notebook-shim=0.2.4
  - nspr=4.35
  - nss=3.101
  - numba=0.60.0
  - numpy=1.26.4
  - oniguruma=6.9.9
  - openjpeg=2.5.2
  - openssl=3.3.1
  - orc=2.0.1
  - overrides=7.7.0
  - packaging=24.1
  - pandas=2.2.2
  - pandoc=3.2
  - pandocfilters=1.5.0
  - pango=1.54.0
  - parso=0.8.4
  - patsy=0.5.6
  - pcre2=10.43
  - perl=5.32.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.3.0
  - pip=24.0
  - pixman=0.43.4
  - pkg-config=0.29.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.2.2
  - poppler=24.04.0
  - poppler-data=0.4.12
  - postgresql=16.3
  - presto=0.7.2
  - proj=9.4.1
  - prometheus_client=0.20.0
  - prompt-toolkit=3.0.47
  - prompt_toolkit=3.0.47
  - psutil=5.9.8
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.22
  - pygments=2.18.0
  - pynndescent=0.5.13
  - pyobjc-core=10.3.1
  - pyobjc-framework-cocoa=10.3.1
  - pyparsing=3.1.2
  - pysocks=1.7.1
  - python=3.10.14
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=2.0.7
  - python-tzdata=2024.1
  - python_abi=3.10
  - pytz=2024.1
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - qtconsole-base=5.5.2
  - qtpy=2.4.1
  - r-abind=1.4_5
  - r-anndata=0.7.5.4
  - r-ape=5.8
  - r-argparse=2.2.3
  - r-arrow=16.1.0
  - r-askpass=1.2.0
  - r-assertthat=0.2.1
  - r-backports=1.5.0
  - r-base=4.3.3
  - r-base64enc=0.1_3
  - r-beeswarm=0.4.0
  - r-bh=1.84.0_0
  - r-bibtex=0.5.1
  - r-bit=4.0.5
  - r-bit64=4.0.5
  - r-bitops=1.0_7
  - r-blob=1.2.4
  - r-boot=1.3_30
  - r-brew=1.0_10
  - r-brio=1.1.5
  - r-broom=1.0.6
  - r-bslib=0.7.0
  - r-cachem=1.1.0
  - r-cairo=1.6_2
  - r-callr=3.7.6
  - r-car=3.1_2
  - r-cardata=3.0_5
  - r-caret=6.0_94
  - r-catools=1.18.2
  - r-cellranger=1.1.0
  - r-checkmate=2.3.1
  - r-circlize=0.4.16
  - r-class=7.3_22
  - r-classint=0.4_10
  - r-cli=3.6.2
  - r-clipr=0.8.0
  - r-clock=0.7.0
  - r-clue=0.3_65
  - r-cluster=2.1.6
  - r-coda=0.19_4.1
  - r-codetools=0.2_20
  - r-coin=1.4_3
  - r-colorspace=2.1_0
  - r-commonmark=1.9.1
  - r-concaveman=1.1.0
  - r-conflicted=1.2.0
  - r-conquer=1.3.3
  - r-corrplot=0.92
  - r-cowplot=1.1.3
  - r-cpp11=0.4.7
  - r-crayon=1.5.3
  - r-credentials=2.0.1
  - r-crosstalk=1.2.1
  - r-crul=1.4.2
  - r-curl=5.1.0
  - r-data.table=1.15.4
  - r-dbi=1.2.3
  - r-dbplyr=2.5.0
  - r-dbscan=1.1_12
  - r-deldir=2.0_4
  - r-dendextend=1.17.1
  - r-desc=1.4.3
  - r-devtools=2.4.5
  - r-diagram=1.6.5
  - r-diffobj=0.3.5
  - r-digest=0.6.35
  - r-doparallel=1.0.17
  - r-dotcall64=1.1_1
  - r-downlit=0.4.4
  - r-dplyr=1.1.4
  - r-dqrng=0.3.2
  - r-dtplyr=1.3.1
  - r-e1071=1.7_14
  - r-ellipsis=0.3.2
  - r-evaluate=0.24.0
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-fastcluster=1.2.6
  - r-fastdummies=1.7.3
  - r-fastmap=1.2.0
  - r-fftwtools=0.9_11
  - r-fields=15.2
  - r-filelock=1.0.3
  - r-findpython=1.0.8
  - r-fitdistrplus=1.1_11
  - r-fnn=1.1.4
  - r-fontawesome=0.5.2
  - r-forcats=1.0.0
  - r-foreach=1.5.2
  - r-foreign=0.8_86
  - r-formatr=1.14
  - r-fs=1.6.4
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-future=1.33.2
  - r-future.apply=1.11.2
  - r-gargle=1.5.2
  - r-generics=0.1.3
  - r-geojson=0.3.5
  - r-geojsonio=0.11.3
  - r-geojsonlint=0.4.0
  - r-geojsonsf=2.0.3
  - r-geometries=0.2.4
  - r-gert=2.0.1
  - r-getopt=1.20.4
  - r-getoptlong=1.0.5
  - r-ggalluvial=0.12.5
  - r-ggbeeswarm=0.7.2
  - r-ggcorrplot=0.1.4.1
  - r-ggforce=0.4.2
  - r-ggfun=0.1.5
  - r-ggnetwork=0.5.13
  - r-ggnewscale=0.4.10
  - r-ggplot2=3.5.1
  - r-ggpubr=0.6.0
  - r-ggrastr=1.0.2
  - r-ggrepel=0.9.5
  - r-ggridges=0.5.6
  - r-ggsci=3.2.0
  - r-ggsignif=0.6.4
  - r-gh=1.4.1
  - r-gitcreds=0.1.2
  - r-globaloptions=0.1.2
  - r-globals=0.16.3
  - r-glue=1.7.0
  - r-goftest=1.2_3
  - r-googledrive=2.1.1
  - r-googlesheets4=1.1.1
  - r-gower=1.0.1
  - r-gplots=3.1.3.1
  - r-gridbase=0.4_7
  - r-gridextra=2.3
  - r-gtable=0.3.5
  - r-gtools=3.9.5
  - r-hardhat=1.4.0
  - r-haven=2.5.4
  - r-hdf5r=1.3.10
  - r-here=1.0.1
  - r-hexbin=1.28.3
  - r-hiddenmarkov=1.8_13
  - r-highr=0.11
  - r-hms=1.1.3
  - r-htmltools=0.5.8.1
  - r-htmlwidgets=1.6.4
  - r-httpcode=0.3.0
  - r-httpuv=1.6.15
  - r-httr=1.4.7
  - r-httr2=1.0.1
  - r-ica=1.0_3
  - r-ids=1.0.1
  - r-igraph=2.0.3
  - r-ini=0.3.1
  - r-ipred=0.9_14
  - r-irdisplay=1.1
  - r-irkernel=1.3.2
  - r-irlba=2.3.5.1
  - r-isoband=0.2.7
  - r-iterators=1.0.14
  - r-jpeg=0.1_10
  - r-jqr=1.3.3
  - r-jquerylib=0.1.4
  - r-jsonify=1.2.2
  - r-jsonlite=1.8.8
  - r-jsonvalidate=1.3.2
  - r-kernlab=0.9_32
  - r-kernsmooth=2.23_24
  - r-knitr=1.47
  - r-labeling=0.4.3
  - r-lambda.r=1.2.4
  - r-later=1.3.2
  - r-lattice=0.22_6
  - r-lava=1.7.3
  - r-lazyeval=0.2.2
  - r-leiden=0.4.3.1
  - r-libcoin=1.0_10
  - r-lifecycle=1.0.4
  - r-listenv=0.9.1
  - r-lme4=1.1_35.3
  - r-lmtest=0.9_40
  - r-locfit=1.5_9.9
  - r-lsei=1.3_0
  - r-lubridate=1.9.3
  - r-magick=2.8.3
  - r-magrittr=2.0.3
  - r-maps=3.4.2
  - r-maptools=1.1_8
  - r-mass=7.3_60
  - r-matrix=1.6_3
  - r-matrixmodels=0.5_3
  - r-matrixstats=1.3.0
  - r-mcmc=0.9_8
  - r-mcmcpack=1.7_0
  - r-memoise=2.0.1
  - r-memuse=4.2_3
  - r-mgcv=1.9_1
  - r-mime=0.12
  - r-miniui=0.1.1.1
  - r-minqa=1.2.7
  - r-mixtools=2.0.0
  - r-modelmetrics=1.2.2.2
  - r-modelr=0.1.11
  - r-modeltools=0.2_23
  - r-multcomp=1.4_25
  - r-munsell=0.5.1
  - r-music=0.2.0
  - r-mvtnorm=1.2_5
  - r-network=1.18.2
  - r-nlme=3.1_165
  - r-nloptr=2.0.3
  - r-nmf=0.21.0
  - r-nnet=7.3_19
  - r-nnls=1.5
  - r-npsurv=0.5_0
  - r-numderiv=2016.8_1.1
  - r-openssl=2.2.0
  - r-optparse=1.7.5
  - r-paralleldist=0.2.6
  - r-parallelly=1.37.1
  - r-patchwork=1.2.0
  - r-pbapply=1.7_2
  - r-pbdzmq=0.3_11
  - r-pbkrtest=0.5.2
  - r-pbmcapply=1.5.1
  - r-pheatmap=1.0.12
  - r-phyclust=0.1_34
  - r-pillar=1.9.0
  - r-pkgbuild=1.4.4
  - r-pkgconfig=2.0.3
  - r-pkgdown=2.0.9
  - r-pkgload=1.3.4
  - r-pkgmaker=0.32.10
  - r-plogr=0.2.0
  - r-plotly=4.10.4
  - r-plyr=1.8.9
  - r-png=0.1_8
  - r-polyclip=1.10_6
  - r-polynom=1.4_1
  - r-praise=1.0.0
  - r-presto=1.0.0
  - r-prettyunits=1.2.0
  - r-proc=1.18.5
  - r-processx=3.8.4
  - r-prodlim=2023.08.28
  - r-profvis=0.3.8
  - r-progress=1.2.3
  - r-progressr=0.14.0
  - r-proj=0.5.0
  - r-promises=1.3.0
  - r-protolite=2.3.0
  - r-proxy=0.4_27
  - r-ps=1.7.6
  - r-purrr=1.0.2
  - r-quantreg=5.98
  - r-r.methodss3=1.8.2
  - r-r.oo=1.26.0
  - r-r.utils=2.12.3
  - r-r6=2.5.1
  - r-ragg=1.3.2
  - r-rann=2.6.1
  - r-rapidjsonr=1.2.0
  - r-rappdirs=0.3.3
  - r-rcmdcheck=1.4.0
  - r-rcolorbrewer=1.1_3
  - r-rcpp=1.0.12
  - r-rcppannoy=0.0.22
  - r-rcpparmadillo=0.12.8.4.0
  - r-rcppeigen=0.3.4.0.0
  - r-rcpphnsw=0.6.0
  - r-rcppml=0.3.7
  - r-rcppparallel=5.1.6
  - r-rcppprogress=0.4.2
  - r-rcpptoml=0.2.2
  - r-rcurl=1.98_1.14
  - r-readr=2.1.5
  - r-readxl=1.4.3
  - r-recipes=1.0.10
  - r-registry=0.5_1
  - r-rematch=2.0.0
  - r-rematch2=2.1.2
  - r-remotes=2.5.0
  - r-repr=1.1.7
  - r-reprex=2.1.0
  - r-reshape2=1.4.4
  - r-reticulate=1.38.0
  - r-rio=1.1.1
  - r-rjags=4_15
  - r-rjson=0.2.21
  - r-rlang=1.1.4
  - r-rle=0.9.2
  - r-rmapshaper=0.5.0
  - r-rmarkdown=2.27
  - r-rngtools=1.5.2
  - r-rocr=1.0_11
  - r-roxygen2=7.3.1
  - r-rpart=4.1.23
  - r-rprojroot=2.0.4
  - r-rspectra=0.16_1
  - r-rsqlite=2.3.4
  - r-rstatix=0.7.2
  - r-rstudioapi=0.16.0
  - r-rsvd=1.0.5
  - r-rtsne=0.17
  - r-rversions=2.1.2
  - r-rvest=1.0.4
  - r-s2=1.1.6
  - r-sandwich=3.1_0
  - r-sass=0.4.9
  - r-scales=1.3.0
  - r-scattermore=1.2
  - r-scatterpie=0.2.3
  - r-scico=1.5.0
  - r-sctransform=0.4.1
  - r-segmented=2.1_0
  - r-selectr=0.4_2
  - r-sessioninfo=1.2.2
  - r-seurat=5.0.3
  - r-seuratobject=5.0.1
  - r-sf=1.0_16
  - r-sfheaders=0.4.4
  - r-shape=1.4.6.1
  - r-shiny=1.8.1.1
  - r-sitmo=2.0.2
  - r-sna=2.7_2
  - r-snow=0.4_4
  - r-sourcetools=0.1.7_1
  - r-sp=2.1_4
  - r-spam=2.10_0
  - r-sparsem=1.83
  - r-spatstat.data=3.0_4
  - r-spatstat.explore=3.2_6
  - r-spatstat.geom=3.2_9
  - r-spatstat.random=3.2_3
  - r-spatstat.sparse=3.0_3
  - r-spatstat.utils=3.0_5
  - r-spdata=2.3.1
  - r-spdep=1.3_5
  - r-squarem=2021.1
  - r-statmod=1.5.0
  - r-statnet.common=4.9.0
  - r-stringi=1.8.4
  - r-stringr=1.5.1
  - r-survival=3.7_0
  - r-svglite=2.1.3
  - r-sys=3.4.2
  - r-systemfonts=1.1.0
  - r-tensor=1.5
  - r-terra=1.7_78
  - r-testthat=3.2.1.1
  - r-textshaping=0.4.0
  - r-th.data=1.1_2
  - r-tibble=3.2.1
  - r-tidyr=1.3.1
  - r-tidyselect=1.2.1
  - r-tidyverse=2.0.0
  - r-tiff=0.1_12
  - r-timechange=0.3.0
  - r-timedate=4032.109
  - r-tinytex=0.51
  - r-triebeard=0.4.1
  - r-tweenr=2.0.3
  - r-tzdb=0.4.0
  - r-units=0.8_5
  - r-urlchecker=1.0.1
  - r-urltools=1.7.3
  - r-usethis=2.2.3
  - r-utf8=1.2.4
  - r-uuid=1.2_0
  - r-uwot=0.1.16
  - r-v8=4.4.2
  - r-vctrs=0.6.5
  - r-vipor=0.4.7
  - r-viridis=0.6.5
  - r-viridislite=0.4.2
  - r-vroom=1.6.5
  - r-waldo=0.5.2
  - r-whisker=0.4.1
  - r-withr=3.0.0
  - r-wk=0.9.1
  - r-writexl=1.5.0
  - r-xfun=0.45
  - r-xml2=1.3.6
  - r-xopen=1.0.1
  - r-xtable=1.8_4
  - r-yaml=2.3.8
  - r-zeallot=0.1.0
  - r-zip=2.3.1
  - r-zoo=1.8_12
  - re2=2023.09.01
  - readline=8.2
  - referencing=0.35.1
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.18.1
  - scanpy=1.10.1
  - scikit-learn=1.5.0
  - scipy=1.13.1
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - session-info=1.0.0
  - setuptools=70.1.0
  - sigtool=0.1.3
  - six=1.16.0
  - snappy=1.2.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - spdlog=1.13.0
  - sqlite=3.46.0
  - stack_data=0.6.2
  - statsmodels=0.14.2
  - stdlib-list=0.10.0
  - tapi=1100.0.11
  - tbb=2021.12.0
  - terminado=0.18.1
  - threadpoolctl=3.5.0
  - tiledb=2.24.1
  - tinycss2=1.3.0
  - tk=8.6.13
  - tktable=2.10
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.12.5
  - tornado=6.4.1
  - tqdm=4.66.4
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20240316
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - typing_utils=0.1.0
  - tzcode=2024a
  - tzdata=2024a
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.2.2
  - vsearch=2.4.4
  - wcwidth=0.2.13
  - webcolors=24.6.0
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.43.0
  - widgetsnbextension=4.0.11
  - xerces-c=3.2.5
  - xmltodict=0.13.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-libxt=1.3.0
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - yq=3.4.3
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.3.1
  - zstd=1.5.6
